name = "chb"
pages_build_output_dir = "dist"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "learning-center-db"
database_id = "1892f453-237c-4efd-b45f-64a0c79b1be3"
migrations_dir = "migrations"
